declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  type IconProps = SVGProps<SVGSVGElement> & { className?: string; size?: number | string }
  type Icon = FC<IconProps>
  export const Building2: Icon
  export const LayoutDashboard: Icon
  export const DollarSign: Icon
  export const Users: Icon
  export const CalendarDays: Icon
  export const FileText: Icon
  export const MessageSquare: Icon
  export const Wrench: Icon
  export const Store: Icon
  export const Settings: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ShieldCheck: Icon
  export const BookOpen: Icon
  export const X: Icon
  export const Plus: Icon
  export const Clock: Icon
  export const CheckCircle2: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const AlertOctagon: Icon
  export const TrendingUp: Icon
  export const ArrowUpRight: Icon
  export const CalendarCheck: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Loader2: Icon
  export const Search: Icon
  export const Filter: Icon
  export const Download: Icon
  export const Upload: Icon
  export const FolderOpen: Icon
  export const File: Icon
  export const Star: Icon
  export const Phone: Icon
  export const Mail: Icon
  export const Scale: Icon
  export const ChevronDown: Icon
  export const ChevronUp: Icon
  export const Sparkles: Icon
  export const Send: Icon
  export const Bot: Icon
  export const User: Icon
  export const LogOut: Icon
  export const Bell: Icon
  export const Menu: Icon
  export const ArrowLeft: Icon
  export const BarChart3: Icon
  export const Activity: Icon
  export const UserPlus: Icon
  export const Save: Icon
  export const Edit: Icon
  export const Check: Icon
  export const Home: Icon
  export const Info: Icon
  export const Zap: Icon
  export const Shield: Icon
  export const Lock: Icon
  export const Unlock: Icon
  export const RefreshCw: Icon
  export const Trash2: Icon
  export const ExternalLink: Icon
  export const Copy: Icon
  export const MoreVertical: Icon
  export const MapPin: Icon
  export const Hash: Icon
  export const TrendingDown: Icon
  export const Brain: Icon
  export const Edit2: Icon
  export const Toggle2: Icon
  export const MessageCircle: Icon
  export const Pen: Icon
  export const Globe: Icon
  export const FileCheck: Icon
  export const FilePlus: Icon
  export const Calendar: Icon
  export const CreditCard: Icon
  export const DoorOpen: Icon
  export const Video: Icon
  export const Wallet: Icon
  export const PhoneCall: Icon
  export const Landmark: Icon
  export const Percent: Icon
  export const CircleDot: Icon
  export const ListChecks: Icon
  export const ClipboardList: Icon
  export const KeyRound: Icon
  export const Palette: Icon
  export const BellRing: Icon
  export const Moon: Icon
  export const Sun: Icon
  export const Monitor: Icon
  export const UserCheck: Icon
  export const BadgeCheck: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const BarChart3: Icon
  export const ShieldAlert: Icon
  export const Radio: Icon
  export const RefreshCw: Icon
  export const Waves: Icon
  export const Flame: Icon
  export const Wind: Icon
  export const CloudRain: Icon
  export const Zap: Icon
  export const ExternalLink: Icon
  export const Info: Icon
  export const ChevronDown: Icon
  export const ChevronUp: Icon
}
